In [9]:
from sqlalchemy import create_engine, text
import pandas as pd

engine = create_engine('sqlite:///movies.db')

from sqlalchemy import text


min_year = 2000

query = text("""
SELECT 
    m.title,
    CAST(SUBSTR(m.title, LENGTH(m.title) - 4, 4) AS INTEGER) AS year,
    CAST(AVG(r.rating) AS INT) AS avg_rating_int
FROM movies m
JOIN ratings r ON m.movieId = r.movieId
WHERE CAST(SUBSTR(m.title, LENGTH(m.title) - 4, 4) AS INTEGER) >= :min_year
GROUP BY m.title
ORDER BY RANDOM()
LIMIT 10
""")

results = pd.read_sql_query(query, engine, params={'min_year': min_year})
results

                                 title  year  avg_rating_int
0  A.I. Artificial Intelligence (2001)  2001               3
1    Captain America: Civil War (2016)  2016               3
2                  Intouchables (2011)  2011               4
3                     Sex Drive (2008)  2008               3
4                     Bad Santa (2003)  2003               3
5          Kings of Summer, The (2013)  2013               3
6                  Shadow World (2016)  2016               4
7                  Crimson Peak (2015)  2015               3
8                Equalizer, The (2014)  2014               3
9             Catch and Release (2006)  2006               2

In [10]:
query = text("""
SELECT m.title, AVG(r.rating) as avg_rating
FROM movies m
JOIN ratings r ON m.movieId = r.movieId
GROUP BY m.title
ORDER BY avg_rating DESC
LIMIT 10
""")

top_movies = pd.read_sql_query(query, engine)
top_movies.head()

                              title  avg_rating
0  Zeitgeist: Moving Forward (2011)         5.0
1       Wow! A Talking Fish! (1983)         5.0
2             World of Glory (1991)         5.0
3               Wonder Woman (2009)         5.0
4  Won't You Be My Neighbor? (2018)         5.0

In [12]:

query = text("""
SELECT 
    m.title,
    t.tag,
    CAST(AVG(r.rating) AS INT) AS avg_rating_int
FROM movies m
JOIN ratings r ON m.movieId = r.movieId
JOIN tags t ON m.movieId = t.movieId
GROUP BY m.title, t.tag
ORDER BY RANDOM()
LIMIT 30
""")

movie_tag_ratings = pd.read_sql_query(query, engine)
movie_tag_ratings

,title,tag,avg_rating_int
0,"Pianist, The (2002)",holocaust,4
1,Corpse Bride (2005),visually appealing,3
2,Monty Python and the Holy Grail (1975),England,4
3,Dead Again (1991),memory,3
4,Who Killed Chea Vichea? (2010),procedural,5
5,X-Men: The Last Stand (2006),Hugh Jackman,3
6,Hero (Ying xiong) (2002),martial arts,3
7,Buffalo '66 (a.k.a. Buffalo 66) (1998),avant-garde romantic comedy,3
8,There Will Be Blood (2007),morality,4
9,It Could Happen to You (1994),gambling,3
10,"Triplets of Belleville, The (Les triplettes de...",biking,3
11,"Nightmare Before Christmas, The (1993)",Halloween,3
12,Big Hero 6 (2014),feel-good,3
13,"Talented Mr. Ripley, The (1999)",serial killer,3
14,While You Were Sleeping (1995),coma,3
15,Dark Days (2000),Homeless,3
16,Stand by Me (1986),Stephen King,4
17,Star Trek VI: The Undiscovered Country (1991),Klingons,3
18,The Hunger Games (2012),ending,3
19,"Red Badge of Courage, The (1951)",Civil War,4
20,"Hobbit: The Desolation of Smaug, The (2013)",too long,3
21,Avatar (2009),military,3
22,Harry Potter and the Prisoner of Azkaban (2004),Wizards,3
23,Harry Potter and the Sorcerer's Stone (a.k.a. ...,Wizards,3
24,Mary and Max (2009),poignant,4
25,Pulp Fiction (1994),intelligent,4
26,Very Bad Things (1998),dark comedy,3
27,Pulp Fiction (1994),1990s,4
28,Memento (2000),twist ending,4
29,Aliens (1986),action,3

In [16]:
query = text("""
SELECT
    m.movieID,
    m.title,
    COUNT(r.rating) AS num_ratings
FROM movies m
JOIN ratings r ON m.movieId = r.movieId
JOIN tags t ON m.movieId = t.movieId
GROUP BY m.title, m.movieID
ORDER BY num_ratings DESC
LIMIT 30
""")

top_rated_movies = pd.read_sql_query(query, engine)
top_rated_movies

    movieId                                              title  num_ratings
0       296                                Pulp Fiction (1994)        55567
1      2959                                  Fight Club (1999)        11772
2       260          Star Wars: Episode IV - A New Hope (1977)         6526
3       293  Léon: The Professional (a.k.a. The Professiona...         4655
4       924                       2001: A Space Odyssey (1968)         4469
5      7361       Eternal Sunshine of the Spotless Mind (2004)         4454
6     79132                                   Inception (2010)         3718
7      1732                           Big Lebowski, The (1998)         3392
8      4878                                Donnie Darko (2001)         3161
9       356                                Forrest Gump (1994)         2961
10      110                                  Braveheart (1995)         2370
11     1196  Star Wars: Episode V - The Empire Strikes Back...         2110
12     4226                                     Memento (2000)         2067
13     7153  Lord of the Rings: The Return of the King, The...         1850
14      589                  Terminator 2: Judgment Day (1991)         1792
15       32          Twelve Monkeys (a.k.a. 12 Monkeys) (1995)         1770
16    72998                                      Avatar (2009)         1746
17      593                   Silence of the Lambs, The (1991)         1674
18      541                                Blade Runner (1982)         1612
19     2762                            Sixth Sense, The (1999)         1611
20     1198  Raiders of the Lost Ark (Indiana Jones and the...         1600
21      527                            Schindler's List (1993)         1540
22     1089                              Reservoir Dogs (1992)         1441
23     2571                                 Matrix, The (1999)         1390
24     4993  Lord of the Rings: The Fellowship of the Ring,...         1386
25    68954                                          Up (2009)         1365
26     3578                                   Gladiator (2000)         1360
27      318                   Shawshank Redemption, The (1994)         1268
28       50                         Usual Suspects, The (1995)         1224
29     1200                                      Aliens (1986)         1134

In [21]:
from sqlalchemy import text
import pandas as pd

query = text("""
SELECT 
    m.title,
    t.tag,
    COUNT(*) AS tag_count,
    AVG(r.rating) AS avg_rating,
    COUNT(r.rating) AS num_ratings
FROM movies m
JOIN ratings r ON m.movieID = r.movieID
JOIN tags t ON m.movieID = t.movieID
WHERE m.movieID IN (
    -- Subquery: to 20 most rated movies
    SELECT m.movieId
    FROM movies m
    JOIN ratings r ON m.movieId = r.movieId
    GROUP BY m.movieId
    ORDER BY COUNT(r.rating) DESC
    LIMIT 20
) 
GROUP BY m.title, t.tag
ORDER BY num_ratings DESC, tag_count DESC
LIMIT 50
""")

# Run the query
common_tags = pd.read_sql_query(query, engine)

# Display the results
common_tags

,title,tag,tag_count,avg_rating,num_ratings
0,Star Wars: Episode IV - A New Hope (1977),sci-fi,753,4.231076,753
1,Star Wars: Episode IV - A New Hope (1977),classic sci-fi,753,4.231076,753
2,Fight Club (1999),dark comedy,654,4.272936,654
3,Pulp Fiction (1994),non-linear,614,4.197068,614
4,Pulp Fiction (1994),hit men,614,4.197068,614
5,Pulp Fiction (1994),great soundtrack,614,4.197068,614
6,Pulp Fiction (1994),good dialogue,614,4.197068,614
7,Pulp Fiction (1994),drugs,614,4.197068,614
8,Pulp Fiction (1994),cult film,614,4.197068,614
9,Pulp Fiction (1994),Tarantino,614,4.197068,614
10,Pulp Fiction (1994),Quentin Tarantino,614,4.197068,614
11,Star Wars: Episode IV - A New Hope (1977),space action,502,4.231076,502
12,Star Wars: Episode IV - A New Hope (1977),classic,502,4.231076,502
13,Star Wars: Episode IV - A New Hope (1977),Star Wars,502,4.231076,502
14,Star Wars: Episode IV - A New Hope (1977),EPIC,502,4.231076,502
15,Fight Club (1999),violence,436,4.272936,436
16,Fight Club (1999),twist ending,436,4.272936,436
17,Fight Club (1999),thought-provoking,436,4.272936,436
18,Fight Club (1999),psychology,436,4.272936,436
19,Toy Story (1995),pixar,430,3.920930,430
20,Raiders of the Lost Ark (Indiana Jones and the...,indiana jones,400,4.207500,400
21,Raiders of the Lost Ark (Indiana Jones and the...,archaeology,400,4.207500,400
22,Forrest Gump (1994),touching,329,4.164134,329
23,Forrest Gump (1994),stupid is as stupid does,329,4.164134,329
24,Forrest Gump (1994),shrimp,329,4.164134,329
25,Forrest Gump (1994),lieutenant dan,329,4.164134,329
26,Forrest Gump (1994),heartwarming,329,4.164134,329
27,Forrest Gump (1994),emotional,329,4.164134,329
28,Forrest Gump (1994),bubba gump shrimp,329,4.164134,329
29,Forrest Gump (1994),bittersweet,329,4.164134,329
30,Forrest Gump (1994),Vietnam,329,4.164134,329
31,"Shawshank Redemption, The (1994)",wrongful imprisonment,317,4.429022,317
32,"Shawshank Redemption, The (1994)",prison,317,4.429022,317
33,"Shawshank Redemption, The (1994)",Stephen King,317,4.429022,317
34,"Shawshank Redemption, The (1994)",Morgan Freeman,317,4.429022,317
35,Pulp Fiction (1994),witty,307,4.197068,307
36,Pulp Fiction (1994),violent,307,4.197068,307
37,Pulp Fiction (1994),violence,307,4.197068,307
38,Pulp Fiction (1994),very funny,307,4.197068,307
39,Pulp Fiction (1994),unusual,307,4.197068,307
40,Pulp Fiction (1994),unpredictable,307,4.197068,307
41,Pulp Fiction (1994),unique,307,4.197068,307
42,Pulp Fiction (1994),twist ending,307,4.197068,307
43,Pulp Fiction (1994),travolta,307,4.197068,307
44,Pulp Fiction (1994),thriller,307,4.197068,307
45,Pulp Fiction (1994),thought-provoking,307,4.197068,307
46,Pulp Fiction (1994),suspense,307,4.197068,307
47,Pulp Fiction (1994),stylized,307,4.197068,307
48,Pulp Fiction (1994),stylish,307,4.197068,307
49,Pulp Fiction (1994),storytelling,307,4.197068,307